name: surrender
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip>=20.3
  - numpy>=1.19.2
  - pip:
    - ipython
    - jupyterlab
    - ipywidgets
    - tqdm
    - aabbtree
    - -e .